<a href="https://colab.research.google.com/github/martlegaspi/58013-Linear-Algebra/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
A = np.array([[4,7,8],[9,0,0],[2,3,4]])
print(A)
print(round(np.linalg.det(A)))

[[4 7 8]
 [9 0 0]
 [2 3 4]]
-36


In [7]:
A = np.array([[2,3,-5],[7,1,-2],[-3,4,1]])
print(A)
print(round(np.linalg.det(A)))

[[ 2  3 -5]
 [ 7  1 -2]
 [-3  4  1]]
-140


In [5]:
#Exercise
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A)
print(round(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-14
