<a href="https://colab.research.google.com/github/martlegaspi/58013-Linear-Algebra/blob/main/Laboratory_No10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [30]:
#Coding Activity 10
import numpy as np
arr = []
temp = []
row1 = []
row2 = []
row3 = []
trow1 = []
trow2 = []
trow3 = []
txt = ['The price of flour per sack is','The price of yeast per pack is','The price of one piece of egg is']

while True:
 x = input('\nEnter either q for month 1, w for month 2, e for month 3, or r to solve/exit: ')
 try:

  if x == 'q':
   row1.clear()
   A = None
   x1 = float(input('Enter how many sack of flour: '))
   if x1 >= 0:
    row1.append(x1)
   else:
    print('You did not enter a proper amount')
   y1 = float(input('Enter how many packs of yeast: '))
   if y1 >= 0:
    row1.append(y1)
   else:
    print('You did not enter a proper amount')
   z1 = float(input('Enter how many eggs: '))
   if z1 >= 0:
    row1.append(z1)
   else:
    print('You did not enter a proper amount')
   A = float(input('Enter the amount: '))
   if A >= 0:
    continue
   else:
    print('You did not enter a proper amount')

  elif x == 'w':
   row2.clear()
   B = None
   x2 = float(input('Enter how many sack of flour: '))
   if x2 >= 0:
    row2.append(x2)
   else:
    print('You did not enter a proper amount')
   y2 = float(input('Enter how many packs of yeast: '))
   if y2 >= 0:
    row2.append(y2)
   else:
    print('You did not enter a proper amount')
   z2 = float(input('Enter how many eggs: '))
   if z2 >= 0:
    row2.append(z2)
   B = float(input('Enter the amount: '))
   if B >= 0:
    continue
   else:
    print('You did not enter a proper amount')

  elif x == 'e':
   row3.clear()
   C = None
   x3 = float(input('Enter how many sack of flour: '))
   if x3 >= 0:
    row3.append(x3)
   else:
    print('You did not enter a proper amount')
   y3 = float(input('Enter how many packs of yeast: '))
   if y3 >= 0:
    row3.append(y3)
   else:
    print('You did not enter a proper amount')
   z3 = float(input('Enter how many eggs: '))
   if z3 >= 0:
    row3.append(z3)
   C = float(input('Enter the amount: '))
   if C >= 0:
    continue
   else:
    print('You did not enter a proper amount')

  elif x == 'r':
   print('You solve/exited')
   break

  else:
   print('You did not enter a proper command')

 except:
  print('There was an error')

try:
 arr.append(row1)
 arr.append(row2)
 arr.append(row3)

 i = 0

 while i <= 2:
  temp.clear()
  trow1.clear()
  trow2.clear()
  trow3.clear()
  trow1 = row1.copy()
  trow2 = row2.copy()
  trow3 = row3.copy()
  trow1[i] = A
  trow2[i] = B
  trow3[i] = C
  temp.append(trow1)
  temp.append(trow2)
  temp.append(trow3)
  det = np.linalg.det(temp) / np.linalg.det(arr)
  print(txt[i], round(det, 2), 'pesos')
  i+=1
except:
 print('There was an error')


Enter either q for month 1, w for month 2, e for month 3, or r to solve/exit: 1
You did not enter a proper command

Enter either q for month 1, w for month 2, e for month 3, or r to solve/exit: q
Enter how many sack of flour: q
There was an error

Enter either q for month 1, w for month 2, e for month 3, or r to solve/exit: q
Enter how many sack of flour: 30
Enter how many packs of yeast: 10
Enter how many eggs: 120
Enter the amount: 12500

Enter either q for month 1, w for month 2, e for month 3, or r to solve/exit: w
Enter how many sack of flour: 40
Enter how many packs of yeast: 20
Enter how many eggs: 200
Enter the amount: 18000

Enter either q for month 1, w for month 2, e for month 3, or r to solve/exit: e
Enter how many sack of flour: 50
Enter how many packs of yeast: 40
Enter how many eggs: 360
Enter the amount: 25700

Enter either q for month 1, w for month 2, e for month 3, or r to solve/exit: r
You solve/exited
The price of flour per sack is 330.0 pesos
The price of yeast p