<a href="https://colab.research.google.com/github/martlegaspi/58013-Linear-Algebra/blob/main/Laboratory_No9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
print(np.linalg.det(A))

## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
print(np.linalg.det(B))


3.0000000000000004
-235.0000000000002


In [20]:
#The commutative property of multiplication does not hold!
#AB != BA

A = np.array([[2,3,1],[7,3,2],[8,5,9]])
B = np.array([[8,5,3],[3,2,8],[1,4,8]])

AB = np.dot(A,B)
BA = np.dot(B,A)

print(AB,'\nis not equal\n', BA)

[[ 26  20  38]
 [ 67  49  61]
 [ 88  86 136]] 
is not equal
 [[75 54 45]
 [84 55 79]
 [94 55 81]]


In [21]:
#Associative property of multiplication
#(AB)C=A(BC)

C = np.array([[5,3,7],[9,1,5],[5,2,8]])

BC = np.dot(B,C)

x = np.dot(AB,C)
y = np.dot(A,BC)

print(x, '\nis equal to\n', y)

[[ 500  174  586]
 [1081  372 1202]
 [1894  622 2134]] 
is equal to
 [[ 500  174  586]
 [1081  372 1202]
 [1894  622 2134]]


In [32]:
#Distributive properties
#A(B+C)=AB+AC
#(B+C)A=BA+CA

AC = np.dot(A,C)
CA = np.dot(C,A)

a = np.add(B,C)

x1 = np.dot(A,a)
x2 = np.dot(a,A)

y1 = np.add(AB,AC)
y2 = np.add(BA,CA)

print(x1, '\nis equal to\n', y1)
print('\n', x2, '\nis equal to\n', y2)

[[ 68  31  75]
 [139  77 141]
 [218 133 289]] 
is equal to
 [[ 68  31  75]
 [139  77 141]
 [218 133 289]]

 [[162 113 119]
 [149 110 135]
 [182 116 162]] 
is equal to
 [[162 113 119]
 [149 110 135]
 [182 116 162]]


In [36]:
#Multiplicative identity property
#IA=A and AI=A wherein I is a diagonal matrix

I = np.eye(3,3)

IA = np.dot(I,A)
AI = np.dot(A,I)

print(IA, '\nis equal to\n', A)
print('\n', AI, '\nis equal to\n', A)

[[2. 3. 1.]
 [7. 3. 2.]
 [8. 5. 9.]] 
is equal to
 [[2 3 1]
 [7 3 2]
 [8 5 9]]

 [[2. 3. 1.]
 [7. 3. 2.]
 [8. 5. 9.]] 
is equal to
 [[2 3 1]
 [7 3 2]
 [8 5 9]]


In [41]:
#Multiplicative property of zero
#0A=0 and A0=0

O = np.zeros([3,3])

OA = np.dot(O,A)
AO = np.dot(A,O)

print (OA, '\nis equal to\n', O)
print ('\n', AO, '\nis equal to\n', O)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
is equal to
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
is equal to
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
#Dimension property
#The product of an mxn matrix and an nxk matrix is an mxk matrix
#(3x2) (2x2) = (3x2)

a1 = np.array([[3,2],[8,5],[5,4]])
b1 = np.array([[7,5],[4,9]])
print('a1 =\n', a1)
print('b1 =\n', b1)

ab1 = np.dot(a1,b1)
print('\n(a1)(b1) =\n', ab1)
print('\nThe shape of matrix a1 is', np.shape(a1))
print('The shape of matrix b1 is', np.shape(b1))
print('The shape of matrix (a1)(b1) is', np.shape(ab1))

a1 =
 [[3 2]
 [8 5]
 [5 4]]
b1 =
 [[7 5]
 [4 9]]

(a1)(b1) =
 [[29 33]
 [76 85]
 [51 61]]

The shape of matrix a1 is (3, 2)
The shape of matrix b1 is (2, 2)
The shape of matrix (a1)(b1) is (3, 2)
