<a href="https://colab.research.google.com/github/martlegaspi/58013-Linear-Algebra/blob/main/Laboratory_No3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

#Vector Addition
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

print(A+B+C)

print(np.add(A,np.add(B,C)))

print(np.sum(B))

[ 4  3 -1]
[ 4  3 -1]
2


In [17]:
#Vector Subtraction
print(np.subtract(A,B))

print(A-B)

[-2  1  2]
[-2  1  2]


In [25]:
#Vector Multiplication
print(np.multiply(A,B))

print(A*B)

[[  8   6]
 [-20 -15]]
[[  8   6]
 [-20 -15]]


In [28]:
#Vector Division
print(np.divide(A,B))

print(A/B)

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
print(C//D)

print(np.array(A/B,dtype=int))

[[ 2.   1.5]
 [-0.8 -0.6]]
[[ 2.   1.5]
 [-0.8 -0.6]]
[3. 1. 7.]
[[2 1]
 [0 0]]
