<a href="https://colab.research.google.com/github/martlegaspi/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
#Problem 1
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
D = np.array([[1, 2], [3, 4]])

print('A =\n', A)
print('B =\n', B)
print('C =\n', C)
print('D =\n', D)

a = np.dot(A, B)
b = np.add(D, D)
c = np.multiply(2, C)


print('\n\nAB =\n', a)
print('\nD+D =\n', b)
print('\n2C =\n', c)

A =
 [[1 2 3]
 [4 5 6]]
B =
 [[1 2]
 [3 4]
 [5 6]]
C =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
D =
 [[1 2]
 [3 4]]


AB =
 [[22 28]
 [49 64]]

D+D =
 [[2 4]
 [6 8]]

2C =
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [77]:
#Problem 2
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

print('A =\n', A)
print('B =\n', B)

cross = np.cross(A,B)
print('\nThe cross-product of matrices A and B is:\n', cross)
print('\n Solution:\nLet x be the 1st column, y be the 2nd column, and z be 3rd column')

x = np.array([[7, 4], [9, 8]])
y = np.array([[2, 4], [3, 8]])
z = np.array([[2, 7], [3, 9]])

print('cross product = x-y+z\n', x, '\n-\n', y, '\n+\n', z)
print('\nx = (7*8)-(9*4) =', (7*8)-(9*4))
print('y = -((2*8)-(3*4)) =', -((2*8)-(3*4)))
print('y = (2*9)-(3*7) =', (2*9)-(3*7))

A =
 [2 7 4]
B =
 [3 9 8]

The cross-product of matrices A and B is:
 [20 -4 -3]

 Solution:
Let x be the 1st column, y be the 2nd column, and z be 3rd column
cross product = x-y+z
 [[7 4]
 [9 8]] 
-
 [[2 4]
 [3 8]] 
+
 [[2 7]
 [3 9]]

x = (7*8)-(9*4) = 20
y = -((2*8)-(3*4)) = -4
y = (2*9)-(3*7) = -3
