<a href="https://colab.research.google.com/github/martlegaspi/58013-Linear-Algebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#Question 1
import numpy as np

num = np.array([1,2,3,4,5,6,7,8,9,10])

for i in num:
 x = 1
 print('\nMultiplication Table for', i)
 while x<=10:
  print(np.multiply(x,i))
  x+=1


Multiplication Table for 1
1
2
3
4
5
6
7
8
9
10

Multiplication Table for 2
2
4
6
8
10
12
14
16
18
20

Multiplication Table for 3
3
6
9
12
15
18
21
24
27
30

Multiplication Table for 4
4
8
12
16
20
24
28
32
36
40

Multiplication Table for 5
5
10
15
20
25
30
35
40
45
50

Multiplication Table for 6
6
12
18
24
30
36
42
48
54
60

Multiplication Table for 7
7
14
21
28
35
42
49
56
63
70

Multiplication Table for 8
8
16
24
32
40
48
56
64
72
80

Multiplication Table for 9
9
18
27
36
45
54
63
72
81
90

Multiplication Table for 10
10
20
30
40
50
60
70
80
90
100


In [27]:
#Question 2
num = np.array([1,2,3,4,5,6,7,8,9,10])

for i in num:
 x = 1
 print('\nMultiplication Table for', i)
 while x<=10:
  mul = np.multiply(x,i)
  print(np.multiply(2,mul), '= 2 x',mul)
  x+=1


Multiplication Table for 1
2 = 2 x 1
4 = 2 x 2
6 = 2 x 3
8 = 2 x 4
10 = 2 x 5
12 = 2 x 6
14 = 2 x 7
16 = 2 x 8
18 = 2 x 9
20 = 2 x 10

Multiplication Table for 2
4 = 2 x 2
8 = 2 x 4
12 = 2 x 6
16 = 2 x 8
20 = 2 x 10
24 = 2 x 12
28 = 2 x 14
32 = 2 x 16
36 = 2 x 18
40 = 2 x 20

Multiplication Table for 3
6 = 2 x 3
12 = 2 x 6
18 = 2 x 9
24 = 2 x 12
30 = 2 x 15
36 = 2 x 18
42 = 2 x 21
48 = 2 x 24
54 = 2 x 27
60 = 2 x 30

Multiplication Table for 4
8 = 2 x 4
16 = 2 x 8
24 = 2 x 12
32 = 2 x 16
40 = 2 x 20
48 = 2 x 24
56 = 2 x 28
64 = 2 x 32
72 = 2 x 36
80 = 2 x 40

Multiplication Table for 5
10 = 2 x 5
20 = 2 x 10
30 = 2 x 15
40 = 2 x 20
50 = 2 x 25
60 = 2 x 30
70 = 2 x 35
80 = 2 x 40
90 = 2 x 45
100 = 2 x 50

Multiplication Table for 6
12 = 2 x 6
24 = 2 x 12
36 = 2 x 18
48 = 2 x 24
60 = 2 x 30
72 = 2 x 36
84 = 2 x 42
96 = 2 x 48
108 = 2 x 54
120 = 2 x 60

Multiplication Table for 7
14 = 2 x 7
28 = 2 x 14
42 = 2 x 21
56 = 2 x 28
70 = 2 x 35
84 = 2 x 42
98 = 2 x 49
112 = 2 x 56
126 = 2 x 63


In [12]:
#Question 3
dia = np.eye(4,4)

print(dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
#Question 4
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print('matrix =\n', matrix)
print('\nThe size of the matrix is', np.size(matrix))
print('The shape of the matrix is', np.shape(matrix))
print('The dimension of the matrix is', len(np.shape(matrix)))

matrix =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

The size of the matrix is 12
The shape of the matrix is (3, 4)
The dimension of the matrix is 2


In [26]:
#Question 5
arrayOne = np.array([[5,6,9], [21,18,27]])
arrayTwo = np.array([[15,33,24],[4,7,1]])

print('arrayOne =\n',arrayOne)
print('arrayTwo =\n',arrayTwo)

sum = np.add(arrayOne, arrayTwo)
print('\narrayOne + arrayTwo =\n', sum)

print('\n(arrayOne + arrayTwo)^2 =\n', np.multiply(sum,sum))

arrayOne =
 [[ 5  6  9]
 [21 18 27]]
arrayTwo =
 [[15 33 24]
 [ 4  7  1]]

arrayOne + arrayTwo =
 [[20 39 33]
 [25 25 28]]

(arrayOne + arrayTwo)^2 =
 [[ 400 1521 1089]
 [ 625  625  784]]
