<a href="https://colab.research.google.com/github/martlegaspi/58013-Linear-Algebra/blob/main/Vector%2C_Spaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Row Vector
import numpy as np

A = np.array([4,3])
B = np.array([2, -5])

print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


In [34]:
#Column Vector
import numpy as np

ball1 = np.array([[1],[2],[3]])
print(ball1)

[[1]
 [2]
 [3]]


In [36]:
#Line, Dimension, Size
import numpy as np

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

print(ball1)
print(ball2)

ball = np.shape(ball1)
balls = np.shape(ball2)

z = ball+balls
print(z)

[1 2 3]
[ 0  1 -1]
(3, 3)


In [47]:
#Addition

A = np.array([4, 3])
B = np.array([1, -5])

R = np.add(A, B)

print(R)

[ 5 -2]


In [51]:
#Subtraction

R1 = np.subtract(A, B)
print(R1)

R2 = np.subtract(B, A)
print(R2)

[3 8]
[-3 -8]


In [52]:
#Scalar Product

S = np.array([2])
P = S*A
print(P)

[8 6]


In [61]:
#Dot Product

A = np.array([4, 3])
B = np.array([[2], [-5]])

D = A*B

print(D)

[[  8   6]
 [-20 -15]]


In [101]:
#Property Of Matrix

#Identity Matrix
c = np.eye(3, 3)

print(c)

#Zero Matrix
d = np.zeros([5,5])
print(d)

#Full Matrix
f = np.full((3,3),7)
print(f)

#Transpose Matrix
A = np.array([4,3])
t = np.transpose(A)
print(t)

#Null Matrix
n = np.empty(0)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[4 3]
[]
